openapi: "3.0.0"
info:
  version: 1.0.0
  title: Zoekdienst SC
  license:
    name: MIT
  description: |
    ## Zoekdienst SC

    | Syntax | Description |
    | ----------- | ----------- |
    | Header | Title |
    | Paragraph | Text | 

servers:
  - url: https://zoekdienst.overheid.nl/sru
paths:
  /Search:
    get:
      summary: Producten En Diensten API
      operationId: zoekdienst
      tags:
        - Zoekdienst
      parameters:
        - name: version
          in: query
          description: Welke versie wordt gebruikt
          required: true
          schema:
            type: number
            format: float
            example: 1.2
        - name: operation
          in: query
          description: Welke operatie wil je uitvoeren
          required: true
          schema:
            type: string
            example: searchRetrieve
        - name: x-connection
          in: query
          description: In welke databank wil je zoeken
          required: true
          schema:
            type: string
            example: sc
        - name: query
          in: query
          description: De daadwerkelijke zoekquery
          required: true
          schema:
            type: string
            example: keyword="paspoort"
      responses:
        '200':
          description: De zoekresultaten
          headers:
          content:
            application/xml:
              schema:



